#include "exceptions.hpp"

socket_exception::socket_exception (const char* why){

}
